<h1>Login </h1>
<?php echo $this->escapeHtml($this->messages); ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array( 'action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('usr_name'));
echo $this->formRow($form->get('usr_password'));
echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php // view helper
//    if ($user = $this->identity()) {
//        echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
?>		
 | <a href="<?php echo $this->url('album', array('action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a> 
<?php
//    } else {
//        echo 'Not logged in';
//    }
?>
<p>
	<a href="<?php echo $this->url('album', array('action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |  
	<a href="<?php echo $this->url('album', array('action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>